# Generated by Django 2.2 on 2019-04-09 01:53

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [("crosswalk", "0001_initial")]

    operations = [
        migrations.AddConstraint(
            model_name="entity",
            constraint=models.CheckConstraint(
                check=models.Q(
                    _negated=True,
                    alias_for=django.db.models.expressions.F("uuid"),
                ),
                name="uuid_not_equal_alias",
            ),
        )
    ]
