# Generated by Django 2.0 on 2017-12-05 15:43

import crosswalk.validators
import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crosswalk', '0002_auto_20171205_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='attributes',
            field=django.contrib.postgres.fields.jsonb.JSONField(validators=[crosswalk.validators.validate_shallow_dict]),
        ),
    ]
