# Generated by Django 2.0 on 2017-12-07 14:11

import crosswalk.validators
import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crosswalk', '0003_auto_20171205_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='attributes',
            field=django.contrib.postgres.fields.jsonb.JSONField(validators=[crosswalk.validators.validate_shallow_dict, crosswalk.validators.validate_no_reserved_keys]),
        ),
    ]
