# Generated by Django 2.0 on 2017-12-08 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crosswalk', '0004_auto_20171207_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='alias_for',
            field=models.ForeignKey(blank=True, help_text=('An entity in the same domain whose UUID should supersede', 'this one.'), null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='crosswalk.Entity'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='superseded_by',
            field=models.ForeignKey(blank=True, help_text=('An entity in another domain whose UUID should supersede', 'this one.'), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supersedes', to='crosswalk.Entity'),
        ),
    ]
