# Generated by Django 2.0 on 2017-12-15 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crosswalk', '0005_auto_20171208_1240'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entity',
            options={'verbose_name_plural': 'entities'},
        ),
        migrations.AlterUniqueTogether(
            name='entity',
            unique_together={('domain', 'attributes')},
        ),
    ]
